### ISSUE TITLE
Give ability/opportunity to run all tasks manually

### ISSUE THREAD

**Issue by NobbZ** [rkotze/eye_drops#3]
Sometimes after leaving my place for a while, I'd like to rerun all tests before continuing my work.

Currently I have to kill `eye_drops` and run `mix test` manually and start `eye_drops` again. This is a suboptimal flow.

I think it would be nice to be able to enter some very basic commands to rerun everythink or only a list of tasks.

I do think the easiest way to achieve something similar is to make the prefered way to start `eye_drops` like `iex -S mix eye_drops` and then import a function `eye_run/1` into `iex`s default namespace, such that one can use that function to run either a single task by its `id` or many by providing a list of ids. Also an `eye_run/0` could be used to run all tasks that `eye_drops` knows about.

Of course the name for that function is choosen semi-randomly and everything what makes sense can be used here.

**Comment by rkotze** [comment]
Sorry for slow reply - just back from holiday.

I had similar thoughts about having a rerun of the tests after being distracted with other things. I will look into this soon.
